import React from 'react';
import { Inter } from 'next/font/google';
import PropTypes from 'prop-types';
import './globals.css';

import Background from '../containers/background/background';
import Navbar from './navbar/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Background>
          <Navbar />
          {children}
        </Background>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.object,
    PropTypes.node,
  ]).isRequired,
};

export default RootLayout;
